### ISSUE TITLE
A program on build

### ISSUE THREAD

**Issue by Eureka0225** [svenpaulsen/node-ts3sdk-client#9]
Hi, I want to use the `node-gyp build` to build this project, but I have many error from compiler, I use the msvs2019, npm6.13.7, node13.11.0 and node-gyp6.1.0.
Error looks like:
`D:\node-ts3sdk-client-master\src\argument.cpp(260,43): error C2065: [LOCAL LANGUAGE] [D:\node-ts3sdk-client-master\build\ts3client.vcxproj]`

**Comment by iJosephY** [comment]
Hello,
the project is not maintained at all and it was made for node 8 or 10 i'm not sure
but it is using some deprecated v8 api and old nan version
so building in node > 10 will output errors and fail to build.

i don't have any c++ knowledge but i have been experimenting a bit with the project trying to fix it and update it to latest v8 and nan api so it can be build in node > 12 again
if my experiment succeed i will release the repo publicly and notify you about it 
♥

**Comment by adamk33n3r** [comment]
This might be a node version issue. I know that it works on node v8.17.0

**Comment by Eureka0225** [comment]
> This might be a node version issue. I know that it works on node v8.17.0

a, that's a too old version..

**Comment by adamk33n3r** [comment]
I've made a PR at #11 to support node v12 (the current LTS).
You can use it by using `npm install github:adamk33n3r/node-ts3sdk-client` in the meantime
